project:
  type: website
  output-dir: docs

website:
  title: "GeoBlog"
  navbar:
    right:
      - icon: house-door-fill
        href: https://rodrigobrust.com
      - icon: github
        href: https://github.com/rodreras
      - icon: linkedin
        href: https://linkedin.com/rodrigobrust
format:
  html:
    theme: sandstone
    css: styles.css



